### ISSUE TITLE
20171009补充与调整记录情绪模块，构思调节情绪内容

### ISSUE THREAD

**Issue by lijinyan89** [lijinyan89/emotion-notebook#4]
写出自己的想法吧

**Comment by Lknj** [comment]
这块实现需要根据用户所选信息来返回内容，前面有 产生情绪的原因 这一项，也就是事件了，我们可以调用用户所选信息来组合为整体事件，如：
场景：工作单位   对象：上司  念头：想揍他
原因：他仅仅因为我不帮他接杯水，就没事找事训我（这块是用户输入，还有其他的用户输入，我们无法像单选那样根据用户选择来返回相应信息，这个根据输入来返回，是个难点）
组合为一段： 在 （场景） （对象） （原因），（念头）
调节情绪，仅仅返回内容还不够，让用户对自己的情绪说yes or no 这个挺不错的
然后需要返回调节情绪的方法等一些比较有帮助的内容，返回比较正式，官方，有权威的信息，但是谁也不会喜欢网上那种枯燥的事实，所以把这些信息变为有趣的返回，以让用户微微一笑为目的。

我以上所说是我目前所能做到的

**Comment by lijinyan89** [comment]
@Lknj 
我觉得原因应该与事件分开,这样方便后面找到产生情绪的根本原因。
比如事件是：上司仅仅因为我不帮他接杯水，就没事找事训我。
最好是具体一点的，这个有点概括性。 比如今天因为我做错了什么事情，他今天当着很多同事的面批评我：'....'
原因：我觉得自己丢了面子，大家都会看不起我
原因的原因：他批评了我，就是否定了我的价值。
                     我只要做得有一点不好，大家就会不喜欢我。

如果找到原因的原因，就离发现自动思维很近了。

**Comment by Lknj** [comment]
@lijinyan89 
您的想法更好，看看李珣老师有没有补充的，没有的话就按您的想法来做，这方面您们比我强多了

**Comment by Miss-3278** [comment]
我重新调整了一下日记的设置，大家来看一下

---

场景：（选项）
对象：（选项）
事件：（自己描述，设定字数比如 100 或者 140 ）
情绪：（单选，选项列出几个比较常见有代表性的情绪，有：悲伤、愤怒、焦虑、内疚、恐惧、忧愁……）
念头：（用表单，表单内或者下面附一些例子）
身体反应：（选项）

---

（上面都可以快速填，下面的需要一些思考时间，也是按下暂停键的时候，可以是文字提示）

情绪的原因：我（情绪，自动填上上面情绪部分的选项）因为……（用户填）。
事实和我想象的原因一样吗？（这个是一个追问，可以有选项也可以这么放着，大家看法）
我的念头是否会真的发生：（单选是或否）
对自我情绪的评价：（单选正向或负向，这一块看看能不能最后做一个统计）

---

关于返回我建议根据情绪返回。

这是一个情绪日记，有点在于可以快速记录情绪，并且帮助识别自动思维，用时 3-5 分钟。上面我们的目的已经达到了。最好后面能形成统计，但是我现在没有思路，不知道怎么弄。

返回的东西我想到有意思的东西， 00 [如何识别自动思维？](https://mp.weixin.qq.com/s/mQ3hu-msnp0nH1kMx_pq-g) 这篇文章中提到可以将自动思维形象化。

          2. 将自动思维形象化

         尝试给想要调整的自动思维塑造一个生动的形象，比如，纸老虎、聒噪的青蛙、严厉的老师、无脸人  之类的，诀窍是选择那种看起来很强大，实际上容易怂的形象，嘿嘿嘿。。。每次识觉察到自动思维又在默默推动小球滚过沙池，我们就可以试着跟这个形象开始对话。
         经过一些练习，你也许会发现这个形象越来越具体，也就越容易被识别出来，自己就不容易受它所代表的自动思维所控制。

返回可以这样写（试举一例）：焦虑像一只聒噪的青蛙，请停止聒噪，先跳出井底再说！

也就是说根据情绪，返回一个形象，给出一句话建议。关于如何返回形象和建议：

1. 写几句可以随机组合的万能话，随机跳。

2. 增加给情绪强度打分的选项，比如说 1--10 分或者5个星，然后根据分数返回固定的话。

**Comment by lijinyan89** [comment]
@Miss-3278 
第一部分我觉得差不多可以了，我谈谈我的一点想法
情绪 除单选外也应该有另外填空吧，情绪写得越细化，感受越清楚。
念头 除了动作的具象化，把心理活动也写出来，由易到难。第二部分情绪的原因就可以填更根本的原因了

第二部分我觉得很好，就最后对自我情绪的评价我不是很赞同，因为如果评价是负面的，就似乎很难让人接受，就像对情绪说no一样，负面情绪就会爆炸式的增长。

第三部分我也没想好。你说的这个方法让我想起了前不久看到的一个方法。
我们很多人心里住着一个批评家，记录下每次你心里那个批评家说的话，过一段时间，总结成两三句，三五句，把它们用 《生日快乐》，《小星星》或者《jinggle bells》的曲调唱出来，就会感觉那些话特别可笑。这是一种脱敏疗法

**Comment by Miss-3278** [comment]
@lijinyan89 我解释一下为什么要对情绪进行评价。

想要不为情绪控制，第一步是识别情绪。这是一个关键点，因为很多人都不具备识别情绪的能力，分不清愤怒的自己是不是已经产生了愤怒，因此我们做出情绪的选项。第二步是摆脱和改善。想要摆脱情绪的控制，要经过几个重要节点。一是承认，即是承认这个情绪、承认这个情绪是我的、在情绪的影像下我很难受（身心感受）；二是接受，接受自我与情绪共存；三是允许，允许自己有这样的情绪。比如说不满于父母而产生的愤怒，失恋后而产生的焦虑和恐惧……当我们面对情绪，承认她、允许她、拥抱她的时候，她就会慢慢与你和解，渐渐地，你会感觉到你们两个就像熟悉的朋友，你清楚她的底细，你们之间能够沟通。当你了解她（情绪）的时候，她就像一面镜子，照出你自己，通过你的朋友，你更加了解自己。由此，情绪是一把双刃剑，即使是负面的情绪，也有积极的意义。

至于，是否在情绪中加入评价的部分，这个不重要，想加就加，不想加就不加。统计的想法来自于番茄时钟，统计自己一个月的情绪状态，是正面多还是负面多。每个月一看，是不是负面情绪有所减少。

**Comment by Miss-3278** [comment]
情绪评价因为有统计的部分，可以先不加上去，我们完成最小 MVP

**Comment by lijinyan89** [comment]
@Miss-3278 你说的有道理，我可能有点逃避负面情绪

**Comment by lijinyan89** [comment]
另外00的文章《如何识别自动思维》里引述过的另一篇文章《[警惕信念的苛捐杂税](https://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=2651933574&idx=2&sn=4dc0ee71d7dfc5a532f7ea15cbfdf547&chksm=8bcf0d9ebcb88488cd6dafee20e134b23c70de154e47c0bec8887062c0dd6aac1cf11d9d8927&scene=21#wechat_redirect)》，应该也能够给我们一些启发

“常见的个人信念税

我们倾向于认为，大多数人持有相对正面和现实的核心信念，比如「大多数事情我能够胜任」、「我是有价值的人」，负面的核心信念只在遭遇一些应激事件导致内心痛苦时才表现出来。但只要稍微认真审视一下，或多或少会发现，一些隐蔽的信念在持续发挥着影响。即便优秀富有成效的人，也可能是受类似「我不被接受」之类的负面核心信念所驱动。
认知疗法之父 Aaron Beck 将核心信念分为三类[2]：
无能类核心信念（Helpless Core Beliefs）
我不能胜任
我做事毫无效率
任何事我都做不好
我很无助
我易受伤害
我贫苦
我失控
我是有缺陷的人 （例如，我比不上其他人）
我不够好 （成就方面）
我是失败者
……
不可爱类核心信念（Unlovable Core Beliefs）
我不可爱/不讨人喜欢/不受欢迎/没有吸引力
我是多余的
我被人忽视
我与人不同
我真坏（所以其他人不爱我）
我不够好（所以其他人不爱我）
我必定被拒绝
我必定孤独
……
无价值类核心信念（Worthless Core Beliefs）
我毫无价值
我不被接受
我是废物
我不道德
我很危险
我有罪
……
一眼看上去，大部分的核心信念好像都跟我们关系不大。
真的是这样吗？
想想，你为什么会把工作上的一件小事做得比别人好？
是真正乐于其中吗？还是害怕做不好会有后果？还是别人的称赞会让自己觉得有价值？为什么别人的称赞如此重要？为什么别人实际上没有做出的称赞成为了动力？……继续追问下去，有没有出现上面提到的核心信念？
想想，你为什么会把工作上的一件小事做得不如别人？
是不知道该怎么做吗？是觉得无聊不想做吗？是做得比别人慢吗？……继续追问下去，有没有出现上面提到的核心信念？
再想想，你为什么会在意跟别人比较工作成果？
是因为薪水吗？是因为不想被批评吗？是因为能获得成就感吗？……继续追问下去，有没有出现上面提到的核心信念？”

**Comment by lijinyan89** [comment]
@Miss-3278  评价负面情绪，负面情绪 就成了一个客体，与 个人就分开了。评分便于统计，量化。

**Comment by Miss-3278** [comment]
@lijinyan89 人的思想信念系统确实很重要，一些艰苦的事业或事情都是有坚定信念支撑的。

举例子，去过重庆的渣滓洞，看那些刑具，回顾那一段历史，我不禁先问自己，当我面对这些肉身折磨的时候，我能不能挺得下去，作为一名有血有肉的普通人，我的回答是「可能会」也「可能不会」。我再问自己，那些人为什么能咬牙挺过去，我的答案是——信念，因此我敬佩英烈。信念可以影响行为和感受。

上面的信念的苛捐杂税，可以帮助使用者找到原因的原因，如果没有专业指导，其实原因的原因很难被察觉和发现，在情绪的原因这一部分使用这个，如何？

**Comment by lijinyan89** [comment]
嗯嗯，我也觉得在情绪的原因上可以用这个。还有一些资料可以参考，我明天再找一下。

**Comment by Lknj** [comment]
遇到困难了，下面需要用到选中选项的值，不知如何获取，如何调用

**Comment by Miss-3278** [comment]
@Lknj 能否具体描述一下

**Comment by Lknj** [comment]
<input type="radio" name="" vlaue=""> 
<input type="checkbox" name="" vlaue="">
python如何获取上面的值，或者有没有在html中直接获取的方法
情绪的原因：我（情绪，自动填上上面情绪部分的选项） 就是这一部分不会了，google了好长时间了，没能解决了

**Comment by Lknj** [comment]
<input type="radio" name="" vlaue=""

<input type="checkbox" name="" vlaue=""

如何用python获取上面的值，或者直接在html中获取，google了好长时间，没能解决

情绪的原因：我（情绪，自动填上上面情绪部分的选项）因为……（用户填）。

就是这部分

**Comment by Miss-3278** [comment]
@Lknj @lijinyan89 

先放下这个点，最后有时间再丰富一下。我们改一下设置，把这个作为简单的表单，原来的

         情绪的原因：我（情绪，自动填上上面情绪部分的选项）因为……（用户填）。

改为

        情绪背后的原因：（选项 + 其它）我不能胜任、我不够好、我毫无价值、其它

上面的选项根据认知疗法之父 Aaron Beck 将核心信念，提取出三个最常见的信念。

**Comment by Miss-3278** [comment]
@lijinyan89 

可否还有更加丰富的内容，是否加入情绪评价，并统计？最后形成一个统一概念。

**Comment by lijinyan89** [comment]
@Miss-3278 不好意思，昨天有点忙，上晚自习，今天我把我的想法写一下，然后我们一起看看选择什么内容

**Comment by lijinyan89** [comment]
@Miss-3278 

这是其他的一些资料，但感觉还是三大核心信念更容易理解

贝克将认知过程中的歪曲归纳为五种形式：
认知歪曲

1.任意推断
即在证据缺乏或不充分时便草率地作出结论，如“我是无用的，因为我去买东西时商店已经关门了。”
2.选择性概括
仅依据个别细节而不考虑其他情况便对整个事件作出结论，这是一种瞎子摸象式的、以偏概全的认知方式。如“单位中有许多不学无术的人在工作，这是我做领导的过错。”
3.过度引伸
或称过度泛化，是指在单一事件的基础上作出关于能力、操作或价值的普遍性结论，也就是说从一个琐细事件出发引伸作出的结论。如“因为我不明白这个问题，所以我是一个愚蠢的人。”或“因为打碎了一只碗，所以我不是一个好母亲。”
4.夸大或缩小
对客观事件的意义作出歪曲的评价，如“因为偶然的开玩笑，并无恶意地撒了一次谎，于是认为完全丧失了诚意。”
5.极端的思维
即要么全对，要么全错，病人往往把生活看成非黑即白的单色世界，没有中间色。如没有被聘为电视播音员，从而就产生：“我感到非常沮丧，因为没有什么地方再会聘用我了；我现在连整理房间的能力也没有了，我成为一个无用的人了。”

这个内容要不要加入里面？


 还有一个[自动化思维问卷 ATQ](https://www.wjx.cn/jq/12617323.aspx)



这个是之前一个课上的日记模板


以下是关于你的情绪事件簿，让我们一起回想与检视当时遇到事情时，你的身心是如何应对的？能够想得越仔细，写的越详细，你就能够更了解自己哦！
 
1. 事件发生时间？
   
2. 什么事情？（如：某日游泳课，阿花一直游不好，别人轻轻松松就游完25公尺，自己却怎么练都练不好）
 
3. 发生此经验时身体有何感觉？（如：感觉脸红，全身发热；胃在翻滚，很不舒服）
 
4. 发生此经验时，情绪如何？（如：沮丧、低落、生气、担心）
 
5. 发生此经验时。有何想法？（如：我怎么这么笨，同学一定都在偷偷取笑我；我连游泳这么一点小事都做不好，未来一定什么也做不了。）
 
6. 发生了这个事情之后，我的反应是？（如：我决定再也不要上游泳课了;我觉得这这教练教的很烂，我要换教练）
 
7.你现在写这经验时，身体有何感觉？有何情绪想法？


怎样处理情绪的模板

正念抓虫日记 (每日练习)
 
1/ 今天我遇到的心情事件：
 
2/ 我的感受，想法和反应是？

3/ 虫虫躲在哪里?

注 八大虫虫危机
 
「二分法思考」让人处于非黑即白、非敌即友的强烈对立思考，无法了解另一种思考的可能性。
「过度类化」让人产生以偏盖全的逻辑谬误，产生「总是，一直， 就是， 都这样」的限制。
「选择性摘要」让人挑自己想听的、想看的资料，无法看到其他可能。
「夸大与贬低」要不是放大错误和失败、就是缩小优点和成就，让人一直处在挫折、无助的境地。
「应该与必须」让人不由自主的陷入不合理的要求，没有一天能够满足自己的要求。
「贴标签」让人产生不可磨灭的负向认同，很难看到自己与他人的优点。
「个人化」让人担负不该担负的责任，凡事都往自己的身上揽，直到无法负荷。
「随意推论」让人错把偏见当主见，一直看不清现实。
 
**抓完虫虫后， 请做正念第五课音频练习**
 
4/ 正念练习后，我的新选择(回应)是什么？ 

这八点基本是按贝克的认知扭曲来的

**Comment by lijinyan89** [comment]
1.田捷所讲的《人生脚本》里提到的‘允许’这一方法，可以引入到对情绪的接纳上。

观察自己的身体感受、情绪，并对它们说‘yes’,并告诉自己‘我允许自己有这样的身体感受，情绪’。


2.想法，行为 ，情绪是相互影响的。
![img_4778](https://user-images.githubusercontent.com/17683823/31427702-bd9cfd84-ae9a-11e7-9ce3-f6ca61bc98ab.png)

 





##  **## （1 ）情绪**
**情绪有一定的生理基础。情绪有时候不容易察觉，身体是我们最好的锚点。

- [ 1] 找自己舒服的姿势伸展开来，持续一两分钟，如下图。用骨骼撑起身体，体验身体放松的感觉。身体舒展开来，情绪也会有所缓解。身体容易打断负面的状态，我们有时候心情低落有可能是累了，渴了，饿了。有时候吃顿好的，血糖升高，心情就会很好。

![img_4766](https://user-images.githubusercontent.com/17683823/31428175-7fc75e9e-ae9c-11e7-86e6-3835eb3af9f6.png)



- [ 2]  调整呼吸频率（请务必呼吸）

 焦虑，抑郁就会很少呼吸 不呼吸大脑以为你缺氧快死了

- [ 3] 建立规律的作息饮食习惯

 不一定要早睡，但要规律


- [4 ] 注意体会自己身体与情绪的联系

- [5 ] 可以做练习，接纳自己的身体。
在不是洗澡，化妆的情况下，摸摸自己的脸，眼睛，手，脚，身体，想想它们为我做了多少事情，接受它们，安慰它们。





**情绪是你的朋友，一直陪伴你。

- [ 1] 你觉得它想对你说什么呢

它可能会说：‘我一直被驱赶，我希望你能握住我的手，给我一个拥抱’或者‘我很生气，我什么都不想说’。

- [2 ] 你可以对它说什么来安慰它呢

你可以对它说：‘我知道你很难受，我会一直陪着你。’





## **（2）想法**

- [1 ] 想法的选择按贝克的三大核心信念就很好，也就是情绪背后的原因。

- [2 ] 可以统计经常出现的信念，了解自己持有的信念是什么。统计情绪似乎有点复杂，而且情绪来来去去，很难把握，而信念相对少一些，比较固定，也比较好进行调整。

- [3 ] 

> 事实和我想象的原因一样吗？（这个是一个追问，可以有选项也可以这么放着，大家看法）

> 我的念头是否会真的发生：（单选是或否）

这些信念很多是自己想象的，并不是事实。这些信念存在的问题，可以按照贝克总结的认知歪曲

 五条或八条来诊断。

- [4 ] 要不要先接受自己有这样的信念呢？我不确定

- [ 5] 对消极信念怎么办？

前面提到了两个办法


**将自动思维形象化。

> 尝试给想要调整的自动思维塑造一个生动的形象，比如，纸老虎、聒噪的青蛙、严厉的老师、无脸人

之类的，诀窍是选择那种看起来很强大，实际上容易怂的形象，嘿嘿嘿。。。每次识觉察到自动思维又在默默推动小球滚过沙池，我们就可以试着跟这个形象开始对话。

> 经过一些练习，你也许会发现这个形象越来越具体，也就越容易被识别出来，自己就不容易受它所代表的自动思维所控制。

> 返回可以这样写（试举一例）：焦虑像一只聒噪的青蛙，请停止聒噪，先跳出井底再说！

也就是说根据情绪，返回一个形象，给出一句话建议。关于如何返回形象和建议：

> 写几句可以随机组合的万能话，随机跳。

**将经常出现的消极信念用儿歌唱出来

> 我们很多人心里住着一个批评家，记录下每次你心里那个批评家说的话，过一段时间，总结成两三句，三五句，把它们用

 《生日快乐》，《小星星》或者《jinggle 

> bells》的曲调唱出来，就会感觉那些话特别可笑。这是一种脱敏疗法


- [6 ] -可以将一些消极信念转换成积极信念

找到适合自己的积极信念 。这样的积极信念只与自己有关，与外部世界无关。
这些积极信念 ：不能包含否定词；不能过度夸张；不能过度具体。

比如消极信念是 我什么都做不好，积极信念可以是 我还是有一定能力
消极信念是  我不够好， 积极信念可以是  我还可以。



## **（3）行为**

我们在情绪发生后除了有自动化思维，还有自动的反应。有人会在愤怒时反击，有人在受挫时放弃。
特别是有焦虑，抑郁倾向者会有会有逃避的反应。

![Uploading IMG_4779副本.png…]()

可以在情绪平静下来后想想，我这样的反应会导致怎样的结果。这样做真的好吗？
有没有更好的做法。




关于调节情绪我就想到这些，大家看使用什么内容，怎样实现？

**Comment by Miss-3278** [comment]
@lijinyan89 

我们先回到做 emotion note 最初的想法。从你的需要出发，你觉得自己手写情绪日记太麻烦，而又没有相应需求的 app，于是有了自动化完成情绪日记的最初构想。我们把这一需求抽象为 **记录情绪** --> **发现自动化思维** 。由此我把程序的功能定义为「记录以便于发现」，它的优势在于便捷性，只需要打开程序，3-5 分钟就可以完成记录。

为什么要便捷？首先，情绪很微妙，几种情绪会同时爆发，难以捕捉，因此要迅速判断。其次，功能要区分于日记本身，就是不要写太多的字，尽量简洁有力，问题能够暂停情绪、引起思考即可（不要贪多）。否则，为何要用它？如果能需要写很多字的话，需要消耗太多的认知，那为何不去写一篇专门的情绪感受，或者干脆静一静，另外，在手机上打字太多也不太舒适吧？因此，我把便捷性排在优先位置。

说到这里基本上已经把 app 的功能第一阶段的功能，即最小 app 说全面了。

**关于情绪的调整**。我不建议把情绪的调整在第一阶段就添加加在 app 里面，一是会增加难度，二是我们的内容是拼凑的，时间短，没有办法弄得专业。更加重要的原因是，关于情绪的调整是系统工程，不是捡出一个理论就可以对治的。情绪是个人的，每个人的生活时空环境，接触的人和事物以及自身的信念思维，都是不同的，人们各有各的烦恼，而这些都与情绪有着直接或间接的关系。因此每个人的情绪调整（这里指的是真正的转变）都需要有针对个体本身的对治方案。当然关于这一方面完成第一阶段之后是需要考虑的。

**现在还需要决定的**。关于返回，根据什么返回，返回什么内容。

**Comment by lijinyan89** [comment]
@Lknj @Miss-3278 

> 先放下这个点，最后有时间再丰富一下。我们改一下设置，把这个作为简单的表单，原来的

> 情绪的原因：我（情绪，自动填上上面情绪部分的选项）因为……（用户填）。

> 改为


> 情绪背后的原因：（选项+ 其它）我不能胜任、我不够好、我毫无价值、其它

> 上面的选项根据认知疗法之父

> Aaron Beck 将核心信念，提取出三个最常见的信念。

就按你说的这样返回吧，三个核心信念是否要细化呢，不细化似乎太过笼统。

**Comment by lijinyan89** [comment]
@Lknj @Miss-3278 
关于是否对情绪评价，我还是倾向于不评价，统计就统计核心信念。

**Comment by Miss-3278** [comment]
@lijinyan89 

1. 核心信念如何统计，要把信念都列出来吗？

2. 最后根据什么返回？返回的内容是，一句趣话还是唱歌还是别的？

**Comment by lijinyan89** [comment]
@Miss-3278 

可以情绪和信念都统计。后期可以加上时间，可以统计出哪一个时间段会经常出现某种情绪。比如一般早上心情比较好，或者下午容易生气。

情绪背后的原因，让用户从三大类中选，单选。
三大类下面有一些小点，需要我们选择一些比较常见的原因列出来，大概7，8条。也单选。

统计做成圆盘的形式，三大类做一个统计，发现经常出现的一个大类；然后每一大类各做一个统计，找到每一大类经常出现的信念。返回图表。

不过统计我们现在可以先不管，毕竟要比较长的时间才能统计出结果，才有意义。


我们的mvp还是输入信息，储存信息，然后输出信息。

输出这些信息：
事件：
情绪：
身体反应：
念头：
情绪的原因：
我的念头是否会真的发生：（单选是或否）

**Comment by Miss-3278** [comment]
@lijinyan89 

最后规划处「最小 MVP」需要做的事情，让大家清楚知道要做什么，然后这个 issue 关闭，遇到其他问题再开 issue。

**Comment by lijinyan89** [comment]
最小MVP

1.建立页面

场景：（选项）

对象：（选项）

 事件：（自己描述，设定字数比如100 或者 140 ）

情绪：（单选，选项列出几个比较常见有代表性的情绪，有：悲伤、愤怒、焦虑、内疚、恐惧、忧愁……）
身体反应：（选项）

念头：（用表单，表单内或者下面附一些例子，例子还是用一些行为代替）


排解情绪你要做什么或已经做了什么：（表单，示例：购物，狂吃，运动，看喜剧片）


 情绪背后的原因：（选项 + 其它）我不能胜任、别人都不喜欢我、我毫无价值、其它

用户对情绪背后原因的理解  ：提示“事实和我想象的原因一样吗？”  （表单，用户可以填入回答）


2.将用户输入的信息存入数据库中


3.在页面上显示用户输入的信息

事件+情绪+身体反应+念头+排解情绪你要做什么或已经做了什么+情绪背后原因+用户对情绪背后原因的理解
